dataset: "ace05e"
gpu_device: 0
seed: 42
train_file: "../../../data/processed/ace05ep_bart/train.001.w1.oneie.json"
dev_file: "../../../data/processed/ace05ep_bart/dev.w1.oneie.json"
test_file: "../../../data/processed/ace05ep_bart/test.w1.oneie.json"
finetune_dir: "../../../processed_data/degree_e2e_ace05ep_001/"
train_finetune_file: "../../../processed_data/degree_e2e_ace05ep_001/train_all.pkl"
dev_finetune_file: "../../../processed_data/degree_e2e_ace05ep_001/dev_all.pkl"
test_finetune_file: "../../../processed_data/degree_e2e_ace05ep_001/test_all.pkl"
vocab_file: "../../../processed_data/degree_e2e_ace05ep_001/vocab.json"
output_dir: "../../../models/degree_e2e_ace05ep_003/"
cache_dir: "./cache"
model_name: "/data/msy/models/bart-large"
input_style: ["event_type_sent", "keywords", "template"]
output_style: ["trigger:sentence", "argument:sentence"]
n_negative: 15
max_epoch: 35
warmup_epoch: 5
train_batch_size: 8
eval_batch_size: 12
accumulate_step: 2
learning_rate: 1e-05
weight_decay: 1e-05
grad_clipping: 5.0
beam_size: 1
max_length: 384
max_output_length: 100
ignore_first_header: True
write_file: xxx
e2e_model: "/data/msy/DEGREE/output/degree_e2e_ace05ep_001/e2e_1/best_model.mdl"
no_dev: None